services:

  source_postgres:
    env_file: ".env"
    image: postgres:latest
    container_name: ${DB_HOST}
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  src:
    build:
      context: .
      dockerfile: Dockerfile

    command: [ "python", './src/main.py' ]
    networks:
      - elt_network
    depends_on:
      - source_postgres
    volumes:
      - .:/app
      - ./.env:/app/.env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - src
networks:
  elt_network:
    driver: bridge
